spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # create 경우 종료 후 table drop함
    properties:
      hibernate:
#        sho_sql: true # System.out을 통해서 출력됨
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace