server:
  port: 0 # random port

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true # ??(?? ?????)? ??? ???? ??
    fetch-registry: true # ??? ?? Eureka Server? ???? ?? ?? ??? ?? (30? ??? ???)
    service-url:
      defaultZone: http://localhost:8761/eureka # end-point
