server:
  port: 9001

spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true # ??(?? ?????)? ??? ???? ??
    fetch-registry: true # ??? ?? Eureka Server? ???? ?? ?? ??? ?? (30? ??? ???)
    service-url:
      defaultZone: http://localhost:8761/eureka # end-point
