server:
  port: 8081
spring:
  application:
    name: my-first-name # 대문자로 유레카 이름이됨
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
